inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/hbci/element_groups/generated_element_groups.rb
