AllCops:
  TargetRubyVersion: 2.3

# Style/Documentation:
#   Enabled: false
#
Metrics/LineLength:
  Exclude:
    - spec/support/message_stubs.rb

Metrics/MethodLength:
  Exclude:
    - spec/support/message_stubs.rb
#   Enabled: false
#
# Style/IndentationConsistency:
#   Exclude:
#     - spec/support/message_stubs.rb
