inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Guardfile
    - bankster-hbci.gemspec
    - spec/support/message_stubs.rb
    - spec/support/request_stubs.rb

Style/Documentation:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/RescueStandardError:
  Exclude:
    - lib/bankster/hbci/segment_factory.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*


