inherit_from: .rubocop_todo.yml
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/hbci/element_groups/generated_element_groups.rb

Metrics/LineLength:
  Exclude:
    - spec/support/message_stubs.rb
    - spec/support/request_stubs.rb

Metrics/AbcSize:
  Exclude: 
    - spec/support/message_stubs.rb

Metrics/ParameterLists:
  Exclude:
    - spec/support/message_stubs.rb
    - spec/support/request_stubs.rb

