inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - spec/support/message_stubs.rb

Metrics/MethodLength:
  Exclude:
    - spec/support/message_stubs.rb

Metrics/AbcSize:
  Exclude:
    - spec/support/message_stubs.rb
